### ISSUE TITLE
Jquery error

### ISSUE THREAD

**Issue by mrtinkz** [javve/list.js#555]
trying to load it inside document ready but there seems to be an issue.

```
$(document).ready(function() {

  // Place JavaScript code here...
  
  var options = {
  valueNames: [ 'name', 'city' ]
};

	var hackerList = new List('hacker-list', options);
});
```

```
jquery-3.1.1.min.js:2 jQuery.Deferred exception: Cannot read property 'childNodes' of undefined TypeError: Cannot read property 'childNodes' of undefined
    at Templater.getItemSource (http://localhost:8080/js/lib/list.js:1338:29)
    at init (http://localhost:8080/js/lib/list.js:1307:28)
    at new Templater (http://localhost:8080/js/lib/list.js:1470:3)
    at module.exports (http://localhost:8080/js/lib/list.js:1474:10)
    at Object.start (http://localhost:8080/js/lib/list.js:696:50)
    at new module.exports (http://localhost:8080/js/lib/list.js:904:8)
    at HTMLDocument.<anonymous> (http://localhost:8080/js/main.js:9:19)
    at j (http://localhost:8080/js/lib/jquery-3.1.1.min.js:2:29948)
    at k (http://localhost:8080/js/lib/jquery-3.1.1.min.js:2:30262) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2
jquery-3.1.1.min.js:2 Uncaught TypeError: Cannot read property 'childNodes' of undefined
    at Templater.getItemSource (list.js:1338)
    at init (list.js:1307)
    at new Templater (list.js:1470)
    at module.exports (list.js:1474)
    at Object.start (list.js:696)
    at new module.exports (list.js:904)
    at HTMLDocument.<anonymous> (main.js:9)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)
```

**Comment by segheysens** [comment]
Hey @mrtinkz what does your HTML for the list look like? IF the error is at `Templater.getItemSource`, my guess is that there isn't any `<li>` for the list to reference - the List needs to know what each of the list items should look like and can take that in a number of ways (i.e. an example `<li>` in the list, as an a string in the `options`)

**Comment by mrtinkz** [comment]
Took the example from the list.js.com


```
<div id="hacker-list">

  <input class="search" />
  <span class="sort" data-sort="name">Sort by name</span>
  <span class="sort" data-sort="city">Sort by city</span>

  <ul class="list">
   <li>
     <h3 class="name">Jonny</h3>
     <p class="city">Stockholm</p>
   </li>
   <li>
     <h3 class="name">Jonas</h3>
     <p class="city">Berlin</p>
   </li>
  </ul>
</div>
```

**Comment by segheysens** [comment]
Hm, that's odd. I just tested this (albeit with jQuery 3.2.1 instead of 3.1.1, because that's the version that their CDN is currently hosting), and it works fine. Please check [this Codepen](https://codepen.io/segheysens/pen/Lzgdxm) and let me know if you're able to find any differences.

**Comment by mrtinkz** [comment]
Gosh it was the jade/pug that wasn't properly formatted which caused all this mess, It's working now, thank you for helping me out.
